### ISSUE TITLE
[Q10] Roles related by Projects are not linked (roh:roleOf) to an Organization

### ISSUE THREAD

**Issue by memaldi** [HerculesCRUE/ROH#15]
Roles related by Projects are not linked (roh:roleOf) to an Organization

**Comment by memaldi** [comment]
Same problem at Q28, roles are not linked to their correspondent foaf:Person.

**Comment by memaldi** [comment]
Now I can't see any relation of vivo:Project vivo:relates bfo:BFO_0000023 (role), how could we relate projects and roles?

**Comment by brianjlowe** [comment]
A Role should be connected to a vivo:Project via ro:RO_0000052 (realized in).  A person is bearerOf a Role, which is then realized in a process (vivo:Project).  The realizedIn triples connecting to projects are likely missing from the sample data file as I don't think there are any axioms that will serve as hints to the script to generate them.  I'll look at adding those connections as a supplementary step.

vivo:relates is intended (although the current VIVO OWL file doesn't formalize this) to be used only with instances of vivo:Relationship or its subclasses, such as roh:ProjectContract.  So to represent that a person was designated to have a particular role in a particular project, a roh:ProjectContract could relate a foaf:Person, a Role, and a vivo:Project, but the direct connection between the Role itself and the Project should be via realizedIn.

I was just reviewing a few places where vivo:relates is used in ROH that could be revised slightly to align with VIVO.  I should be committing these proposed revisions to a branch later today.
