### ISSUE TITLE
Atributos rdfs:Literal o xsd:string

### ISSUE THREAD

**Issue by estebansota-gnoss** [HerculesCRUE/ROH#2]
Algunos atributos, como vivo#description  en vivo#Project, están declarados como rdfs:Literal. ¿No deberían ser xsd:string?

**Comment by brianjlowe** [comment]
In general it seems dangerous to replace these uses of rdfs:Literal with xsd:string, as this would unnecessarily preclude literals with language tags.  (Similiar situations occur with properties like pageStart and pageEnd:  while it may seem logical to use xsd:integer here, this precludes listing an articles startPage as "xviii", for example.)

It does seem more likely that things like bibo:lccn, oclcnum, issn, eissn, eanucc might have range of xsd:string, but they seem not to be defined that way in BIBO.  Changing them here might lead to problems with integrating external data.
