### ISSUE TITLE
consistency errors

### ISSUE THREAD

**Issue by spitxa** [HerculesCRUE/ROH#35]
running the hermit reasoner finds out several consistency errors. we are still not sure if they are come from ontology 1, ontology 2 or the final merged ontology. tomorrow we are going to discuss it between ontology 1 and 2 designers and try to find out.

**Comment by brianjlowe** [comment]
My inconsistency list had somehow cleared earlier, but I see these now too after restarting Protege.  It looks to be a problem in the merge -- specifically, in ib-hercules agents "fund," while in GnossDeustoOnto funding programs and funding sources (non-agents) do the funding, and they are in turn "promoted by" the funding agencies.

It looks like I can resolve the inconsistency by pulling out a few domain/range axioms that came in with the merge.

**Comment by brianjlowe** [comment]
OK, disregard the above :)  What I was seeing again this morning should already have been resolved in issue #27.  In my pre-coffee state I didn't notice that I had a dirty working copy.  Running Hermit again on the current state of the main branch, it's not reporting inconsistencies, but I'm suspicious that something is just crashing in Protege (surprise!)

I'll go run the reasoning outside Protege and see what I find; I'm also happy to look at the inconsistencies you're seeing if you want to paste them in this issue.

**Comment by brianjlowe** [comment]
Hermit now reports consistency on both the TBox in isolation and the knowlege base including the sample ABox data.
