### ISSUE TITLE
university-hr-es.ttl: this module in the ontology includes concepts beyond human resources

### ISSUE THREAD

**Issue by dipina** [HerculesCRUE/ROH#44]
Not aligned entities of this ontology for Spanish system with CORE one, besides encompases all academic domain not focused on human resources. It includes all the extensions specific for Spain, e.g. KnowledgeArea, ProjectClassification. It should be similar to the UK case, should only limit to model Positions

**Comment by brianjlowe** [comment]
Now contains only the position hierarchy.
