### ISSUE TITLE
Why does roh:Metric inherit from Information Content Entity?

### ISSUE THREAD

**Issue by dipina** [HerculesCRUE/ROH#45]
Unclear to us whether it should inherit from that base class and not directly from owl:Thing

**Comment by brianjlowe** [comment]
I think roh:Metric is essentially a subclass of iao:TimeStampedMeasurementDatum. This is a subclass of InformationContentEntity:

http://www.ontobee.org/ontology/OBI?iri=http://purl.obolibrary.org/obo/IAO_0000582

(Even without the timestamp to retain the functionality of asio:QualifiedValue, MeasurementDatum is still a subclass of InformationContentEntity.  It's hard to imagine what else roh:Metric could be in the OBO world.)

The full IAO/OBI model for timestamped measurements is quite verbose, but perhaps a model for future expansion:

https://ddooley.github.io/docs/data-time-stamped/#

**Comment by dipina** [comment]
OK understood, therefore the correct think would be then to specify roh:Metric as subclass of iao:TimeStampedMeasurementDatum
