### ISSUE TITLE
Name homogeneously all subtypes of Thesis, i.e. remove "s" at the end of Bachelors and Masters theses

### ISSUE THREAD

**Issue by dipina** [HerculesCRUE/ROH#48]

**Comment by brianjlowe** [comment]
Fixed, but according to standard usage in English where constructions like "bachelor's degree", "master's degree", "bachelor's thesis" and "master's thesis" use the possessive, while only the full name of a specific degree itself does not, e.g. "Bachelor of Arts (B.A.)".  The majority of the entities were already named according this convention.
