### ISSUE TITLE
Hierarchy of Status new entity, should it be the same for Reports, Projects, Patents, Evaluations? 

### ISSUE THREAD

**Issue by dipina** [HerculesCRUE/ROH#50]
Status not linked with  with Document, which includes all types of reports.

**Comment by brianjlowe** [comment]
On one hand, it would make sense to have a hierarchy with siblings ProjectStatus, PatentStatus, Evaluations but this would then require replicating the statuses that exist in common (e.g. Accepted, Rejected would be splint into AcceptedPatent, AcceptedReport) or having multiple inheritance.

What seems like the simplest/cleanest solution would be to:
a. leave the classes as direct children of Status
b. update the ranges of the status properties to specify unions of the subclasses.  E.g. :patentStatus would have range unionOf(Submitted, Accepted, Rejected) while :projectStatus would have range unionOf(Open, Closed, ProposalSubmitted, Rejected).  This would actually preserve the overall flavor of the original enumerated datatype values.
c. rename :reportStatus property to :documentStatus and apply it to all Documents, not just Reports.

**Comment by dipina** [comment]
I think that you suggestion is the most elegant and sensible. Please apply it!
