### ISSUE TITLE
roh:KnowledgeArea should be renamed roh:AcademicSubject

### ISSUE THREAD

**Issue by dipina** [HerculesCRUE/ROH#52]
Still a new type of concept name roh:KnowledgeArea should be kept

**Comment by brianjlowe** [comment]
I don't really understand this issue, which sounds like the exact opposite of row 60 on the spreadsheet: "AcademicSubject rename   to KnowledgeArea".

Is the idea to restore AcademicSubject as the parent of BachelorsDegreeSubject, MastersDegreeSubject, etc., and keep it distinct from KnowledgeArea?  Would they be sibling children of skos:Concept?

**Comment by dipina** [comment]
For us, AcademicSubject is a type of Concept. Probably all these subcategories of Concept should have better been ConceptScheme subclasses. For us KnowledgeArea is a different type of concept. For instance, UNESCO codes, and its vertical module should include instances of type KnowledgeArea. In one case we are modelling AcademicSubjects, creating a taxonomy of AcademicSubjects, e.g. subjects taught in degrees, in the other one, research/domain disciplines. I hope that it is clearer
