### ISSUE TITLE
Hay atributos del tipo rdfs:Literal que deberían ser del tipo xsd:string

### ISSUE THREAD

**Issue by alvaropalacios-gnoss** [HerculesCRUE/ROH#7]
Los atributos de tipo rdfs:Literal pueden ser tanto números enteros como strings. Sin embargo, como estos atributos son textos, deberían ser del tipo xsd:string.

Esto ocurre en:
- <http://purl.org/roh/mirror/vivo#Project> en el atributo: <http://purl.org/roh/mirror/vivo#description>
- 	<http://purl.org/roh/mirror/foaf#Person> en el atributo <http://purl.org/roh/mirror/foaf#name>
- 	<http://purl.org/roh/mirror/bibo#Conference> en los atributos <http://purl.org/roh/mirror/vivo#description> y <http://purl.org/roh/mirror/vivo#contactInformation>
- 	<http://purl.org/roh/mirror/bibo#Book> en los atributos <http://purl.org/roh/mirror/vivo#placeOfPublication>, <http://purl.org/roh/mirror/bibo#edition> y <http://purl.org/roh/mirror/bibo#Iccn>
- 	<http://purl.org/roh/mirror/bibo#BookSection> en los atributos <http://purl.org/roh/mirror/bibo#pageStart>, <http://purl.org/roh/mirror/bibo#pageEnd>, <http://purl.org/roh/mirror/bibo#edition> y <http://purl.org/roh/mirror/vivo#placeOfPublication>
- 	<http://purl.org/roh#Activity> en los atributos <http://purl.org/roh/mirror/vivo#description> y <http://purl.org/roh/mirror/vivo#contactInformation>
- 	<http://purl.org/roh/mirror/bibo#Periodical> en los atributos <http://purl.org/roh/mirror/bibo#eissn>, <http://purl.org/roh/mirror/bibo#issn> y <http://purl.org/roh/mirror/bibo#oclcnum>
- 	<http://purl.org/roh/mirror/vivo#AcademicDegree> en el atributo <http://purl.org/roh/mirror/vivo#abbreviation>
- 	<http://purl.org/roh#PhDThesis> en los atributos <http://purl.org/roh/mirror/vivo#placeOfPublication> y <http://purl.org/roh/mirror/vivo#abbreviation>
- 	<http://purl.org/roh#DegreeThesis> en los atributos <http://purl.org/roh/mirror/vivo#placeOfPublication> y <http://purl.org/roh/mirror/vivo#abbreviation>
- 	<http://purl.org/roh/mirror/bibo#AcademicArticle> en los atributos <http://purl.org/roh/mirror/bibo#eanucc13>, <http://purl.org/roh/mirror/bibo#pageStart> y <http://purl.org/roh/mirror/bibo#pageEnd>
- 	<http://purl.org/roh/mirror/vivo#ConferencePaper> en los atributos <http://purl.org/roh/mirror/bibo#pageStart> y <http://purl.org/roh/mirror/bibo#pageEnd>

**Comment by brianjlowe** [comment]
See issue #7.  It seems that most of these (such as description, abbreviation) would lead to problems with data that use language tags on these literals (which would have xsd:langString in RDF 1.1).  Others (like lccn, issn) seem on the surface to be compatible with a range of xsd:string, but since they are not defined that way in BIBO, there may be situations we're not imagining -- or at the very least we would be inviting inconsistencies with data integrated from other source.

It seems much safer to leave them alone.
