### ISSUE TITLE
Mismatch entre distintas documentaciones de la ontología (roh:Accreditation)

### ISSUE THREAD

**Issue by ocorcho** [HerculesCRUE/ROH#79]
Estamos usando como base para entender la ontología este  
[documento](https://github.com/HerculesCRUE/ROH/blob/main/docs/1-%20OntologyDocumentation.pdf) y este [esquema](https://github.com/HerculesCRUE/ROH/blob/main/roh/modules/core/doc/roh-core.xlsx). Sin embargo, estamos detectando algunas diferencias entre ellos, y querríamos saber cuál es la última versión:

Por ejemplo, para la clase roh:Accreditation:

- Según el pdf, hay una object property llamada vivo:hasGoverningActivity, pero tanto en la implementación en OWL de la ontología como en el esquema xlsx se llama vivo:hasGoverningAuthority.

- Tanto en el esquema xlsx como en la implementación de la ontología, esta clase tiene una subclase llamada roh:SealOfQuality, que no aparece en la doc del pdf

¿Podríais indicarnos cuál es la documentación más actualizada o actualizarla de acuerdo con lo que se considere final?

**Comment by HerculesCRUE** [comment]
Hola Oscar, 
Ya se que todavia tenemos pendiente la otra cuestión. Añado a la oficina de proyecto para que nos ayude con el seguimiento de la misma.

En cuanto a tu pregunta actual, me indican que actualizan la información esta misma semana y nos informan cuando este hecha.

Muchas gracias 
Reyes

**Comment by memaldi** [comment]
Hola Oscar, 

Gracias por detectar el error. Hemos resuelto los problemas en la documentación. Concretamente:

* vivo:hasGoverningAuthority es la object property que liga Acreditation con Organization, era un error el nombre vivo:hasGoverningActivity, fallo en trasladar lo que está en la ontología a la documentación.
* Hemos añadido a la documentación de roh:Accreditation la subclase roh:SealOfQuality

La última versión de la documentación actualizada puede encontrarse en https://github.com/HerculesCRUE/ROH/blob/main/docs/1-%20OntologyDocumentation.pdf

Un saludo.

**Comment by ocorcho** [comment]
Ok. Cerramos el issue entonces.
