### ISSUE TITLE
Hay atributos del tipo owl:Thing

### ISSUE THREAD

**Issue by alvaropalacios-gnoss** [HerculesCRUE/ROH#8]
Hay atributos de tipo owl:Thing y esto es un tipo muy general. Se tiene que especificar el tipo.

Esto ocurre en:
- <http://purl.org/roh/mirror/foaf#Person> en los atributos: <http://purl.org/roh/mirror/foaf#img>, <http://purl.org/roh/mirror/foaf#mbox> y <http://purl.org/roh/mirror/foaf#homepage>
- 	<http://purl.org/roh#Accreditation> en el atributo <http://purl.org/roh/mirror/vivo#hasSubjectArea>
- 	<http://purl.org/roh/mirror/bibo#Conference> en los atributos <http://purl.org/roh/mirror/vivo#abbreviation>, <http://purl.org/roh/mirror/vivo#hasSubjectArea> y <http://purl.org/roh/mirror/obo/ro#RO_0001025>
- 	<http://purl.org/roh/mirror/bibo#Book> en el atributo <http://purl.org/roh/mirror/bibo#authorList>
- 	<http://purl.org/roh/mirror/bibo#BookSection> en el atributo <http://purl.org/roh/mirror/bibo#authorList>
- 	<http://purl.org/roh#Activity> en los atributos <http://purl.org/roh/mirror/vivo#dateTimeInterval>, <http://purl.org/roh/mirror/vivo#hasSubjectArea> y <http://purl.org/roh/mirror/obo/ro#RO_0001025>
- 	<http://purl.org/roh#PhDThesis> en el atributo <http://purl.org/roh/mirror/bibo#authorList>
- 	<http://purl.org/roh#DegreeThesis> en el atributo <http://purl.org/roh/mirror/bibo#authorList>
- 	<http://purl.org/roh/mirror/bibo#AcademicArticle> en el atributo <http://purl.org/roh/mirror/bibo#authorList>
- 	<http://purl.org/roh/mirror/vivo#ConferencePaper> en el atributo <http://purl.org/roh/mirror/bibo#authorList>

**Comment by brianjlowe** [comment]
While many of these are fixable, the original ontology does retain the unionOf(rdf:List, rdf:Seq) range for bibo:authorList while curiously restricting to rdf:Seq in the restrictions above.  Protege seems not to like the OWL Full-ish use of the RDF vocabulary here, and shows owl:Thing instead of rdf:Seq.
