### ISSUE TITLE
vivo:hasSubjectArea vs roh:hasKnowledgeArea

### ISSUE THREAD

**Issue by ocorcho** [HerculesCRUE/ROH#80]
En la documentación de la ontología se utiliza la object property vivo:hasSubjectArea, que no está definida en la ontología ROH (aunque procede de vivo). 

En la documentación aparece para las clases:

- roh:Accreditation
- vivo:AdvisingRelationship
- vivo:Contract
- roh:ReservationRelationship

¿Es posible que realmente se trate de la propiedad roh:hasKnowledgeArea que ha sido definida en ROH?

**Comment by mpuerta004** [comment]
Si, efectivamente se trata de la propiedad roh:hasKnowledgeArea. Se ha corregido en la documentación, en el fichero [OntologyDocumentation](https://github.com/HerculesCRUE/ROH/blob/main/docs/1-%20OntologyDocumentation.pdf). También se ha revisado este documento con el objetivo de ponerlo al día con las ultimas actualizaciones de la ontología. 

Un saludo.
