### ISSUE TITLE
Clases desaparecidas

### ISSUE THREAD

**Issue by fyedro** [HerculesCRUE/ROH#81]
En la última versión de la documentación de la ontología han desaparecido varias clases, entre ellas vivo:Project y roh:Activity, aunque siguen incluidas en el índice.

**Comment by mpuerta004** [comment]
No han desaparecido, son subclases de bfo:BFO_0000015 (process), y puedes encontrarlas en esta tabla.

**Comment by fyedro** [comment]
Ok, muchas gracias. Solo habría que actualizar el índice entonces.
